import numpy as np
import random
n=int(input())
A=np.random.randint(0,20,n)
print(A)
B=np.random.randint(0,20,n)
print(B)
C=np.add(A,B)
print("Сложение \n",C)
k=int(input("множитель k \n"))
D=np.multiply(A,k)
print(D)
t=int(input("делитель t \n"))
E=np.divide(A,t)
print(E)

print("Введите количество строк и стобцов через пробел")
m, n=map(int, input().split())
A1=np.random.randint( 1, 20, (m, n))
print (A1)
B1=np.random.randint( 1, 20, (m, n))
print (B1)
C1=np.add(A1,B1)
print("Сложение \n",C1)
D1=np.subtract(B1,A1)
print("Вычитание\n", D1)
E1=np.transpose(A1)
print("Транспонирование 1\n", E1)

A2=np.random.randint( 1, 20, (m, m))
print("Новая кв. матрица n ", A2)
k=int(input("1 в степени k \n"))
F=np.linalg.matrix_power(A2,k)
print(F)
